spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db7?serverTimezone=CST
    username: root
    password: 100861
mybatis:
  configuration:
    map-underscore-to-camel-case: true